### ISSUE TITLE
panic when send SIGINT to headless server

### ISSUE THREAD

**Issue by qingyunha** [go-delve/delve#1633]
1. What version of Delve are you using (`dlv version`)?
 Delve Debugger
Version: 1.2.0
Build: dcc1030d18f876823ccd616b6af2fff504e1509a

2. What version of Go are you using? (`go version`)?
go version go1.12.4 linux/amd64

3. What operating system and processor architecture are you using?
linux 5.1.3-arch1-1-ARCH  x86_64

4. What did you do?
```sh
$ ./dlv exec --headless ./p
API server listening at: 127.0.0.1:36205

```
then
```sh
kill -SIGINT `pgrep dlv`
```

5. What did you expect to see?
dlv  exit

6. What did you see instead?
```sh
panic: accept tcp 127.0.0.1:36205: use of closed network connection

goroutine 15 [running]:
github.com/go-delve/delve/service/rpccommon.(*ServerImpl).Run.func1(0xc000061200)
	/home/taoqy/go/src/github.com/go-delve/delve/service/rpccommon/server.go:155 +0x137
created by github.com/go-delve/delve/service/rpccommon.(*ServerImpl).Run
	/home/taoqy/go/src/github.com/go-delve/delve/service/rpccommon/server.go:145 +0x4af
```

**Comment by qingyunha** [comment]
This may be caused by  `ServerImpl.Stop` doesn't close the `stopChan`. I don't know why the test `s.config.AcceptMulti` is needed.

https://github.com/go-delve/delve/blob/dcc1030d18f876823ccd616b6af2fff504e1509a/service/rpccommon/server.go#L87-L94
