### ISSUE TITLE
Nil dereference during getting lineinfo from compilation unit

### ISSUE THREAD

**Issue by nd** [go-delve/delve#1720]
Got an error report from a GoLand user, unfortunatelly no steps to reproduce, debugger logs, or sources. Also the code was changed since then, but maybe it is still relevant/useful. They got the following error with delve build on revision a82e6d69875ed11a0bb3b80d15efba4b4722106e and go 1.12.9:

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x42a467a]
     
    goroutine 5 [running]:
    github.com/go-delve/delve/pkg/proc.(*BinaryInfo).loadDebugInfoMapsCompileUnit(0xc0000da500, 0xc0001764a0, 0xc000102630, 0xc0000a83f0, 0xc0021dc990)
        /opt/buildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/bininfo.go:1473 +0x10ca
    github.com/go-delve/delve/pkg/proc.(*BinaryInfo).loadDebugInfoMaps(0xc0000da500, 0xc000102630, 0xc000414000, 0x17df84, 0x17df84, 0xc0000b7560, 0xc0000a8360)
        /opt/buildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/bininfo.go:1316 +0x5ae
    created by github.com/go-delve/delve/pkg/proc.loadBinaryInfoMacho
        /opt/buildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/bininfo.go:1120 +0x323

Reportedly update to go1.13.1 fixed the problem.

**Comment by aarzilli** [comment]
Could be something weird involving cgo.
