### ISSUE TITLE
how to debug program that has stdin parameters input?

### ISSUE THREAD

**Issue by wwts17** [go-delve/delve#2060]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.4.0
Build: $Id: 67422e6f7148fa1efa0eac1423ab5594b223d93b $
```
2. What version of Go are you using? (`go version`)?
```
go version go1.14.2 darwin/amd64
```
3. What operating system and processor architecture are you using?
```
Macbook pro 2015 Intel Core i5
MacOS 10.15.4
```
4. What did you do?
I can run my project. Input the command 
```
dlv debug -- --DEBUGER=true --CONFIGPATH=/Users/wwts17/Projects/manager-adapter-serv/etc/config.dev.json go run main.go
```
I try  to use dlv debug my program under my project path
```
dlv debug -- --DEBUGER=true --CONFIGPATH=/Users/wwts17/Projects/manager-adapter-serv/etc/config.dev.json
(dlv) break main.main
Breakpoint 1 set at 0x1aa6c08 for main.main() ./main.go:8
(dlv)
```
5. What did you expect to see?
exec debug
6. What did you see instead?
```
(dlv) break main.main
Breakpoint 1 set at 0x1aa6c08 for main.main() ./main.go:8
(dlv) c
> [unrecovered-panic] runtime.fatalpanic() /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:1189 (hits goroutine(1):1 total:1) (PC: 0x103ac20)
Warning: debugging optimized function
	runtime.curg._panic.arg: interface {}(string) "open : no such file or directory"
  1184:	// fatalpanic implements an unrecoverable panic. It is like fatalthrow, except
  1185:	// that if msgs != nil, fatalpanic also prints panic messages and decrements
  1186:	// runningPanicDefers once main is blocked from exiting.
  1187:	//
  1188:	//go:nosplit
=>1189:	func fatalpanic(msgs *_panic) {
  1190:		pc := getcallerpc()
  1191:		sp := getcallersp()
  1192:		gp := getg()
  1193:		var docrash bool
  1194:		// Switch to the system stack to avoid any stack growth, which
(dlv)
panic: open : no such file or directory

goroutine 1 [running]:
main/common.init.0()
	/Users/wwts17/Projects/manager-adapter-serv/src/main/common/conf_manager.go:62 +0x310
Process 2366 has exited with status 2
(dlv)
```

**Comment by chainhelen** [comment]
@wwts17 You can see FAQ: [How can I use Delve to debug a CLI application?](https://github.com/go-delve/delve/blob/master/Documentation/faq.md#how-can-i-use-delve-to-debug-a-cli-application)

**Comment by aarzilli** [comment]
All I'm seeing is a panic in your code.

**Comment by wwts17** [comment]
@aarzilli 
```
// Load Conf From File 
func init() {
	CONFIGPATH = strings.ToLower(os.Getenv("CONFIGPATH"))
	DUGGER = os.Getenv("DUGGER")

	data, err := ioutil.ReadFile(CONFIGPATH)
	if err != nil {
		panic(err)
	}
	err = json.Unmarshal(data, &MyConfigInfo)
	if err != nil {
		panic(err)
	}
}
```
the panic from here. that look like don't be loaded the environment  parameters.

**Comment by chainhelen** [comment]
1.
```
dlv debug -- --DEBUGER=true --CONFIGPATH=/Users/wwts17/Projects/manager-adapter-serv/etc/config.dev.json go run main.go
```
If you want read parameters from cli, should use [flag](https://golang.org/pkg/flag/) of golang.


2. Or from `os env`,  it should be 
```
export DEBUGER=true && export CONFIGPATH=/Users/wwts17/Projects/manager-adapter-serv/etc/config.dev.json && dlv debug
```
