### ISSUE TITLE
panic: attempting to open file Delve cannot parse

### ISSUE THREAD

**Issue by kcubeterm** [go-delve/delve#2269]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
```sh
$ dlv version
Delve Debugger
Version: 1.5.1
Build: $Id: bca418ea7ae2a4dcda985e623625da727d4525b5 $
```
2. What version of Go are you using? (`go version`)?
```sh
$ go version
go version go1.15.5 android/arm64
```

3. What operating system and processor architecture are you using?
OS: Android pie
Arch: aarch64
4. What did you do?
Official golang hello example. 
```sh
dlv debug ./hello
panic: attempting to open file Delve cannot parse

goroutine 1 [running]:
github.com/go-delve/delve/service/debugger.verifyBinaryFormat(0x400003a1e0, 0x4d, 0x0, 0x0)
        /data/data/com.termux/files/home/go/src/github.com/go-delve/delve/service/debugger/debugger_unix.go:36 +0x120
github.com/go-delve/delve/service/debugger.(*Debugger).Launch(0x4000200a80, 0x40000745c0, 0x1, 0x1, 0x55a26d906d, 0x1, 0x1, 0x55a2241024, 0x73304145c0)
        /data/data/com.termux/files/home/go/src/github.com/go-delve/delve/service/debugger/debugger.go:225 +0x40
github.com/go-delve/delve/service/debugger.New(0x4000254000, 0x40000745c0, 0x1, 0x1, 0x0, 0x0, 0x0)
        /data/data/com.termux/files/home/go/src/github.com/go-delve/delve/service/debugger/debugger.go:176 +0x464
github.com/go-delve/delve/service/rpccommon.(*ServerImpl).Run(0x40002009c0, 0x40002009c0, 0x40002285a0)
        /data/data/com.termux/files/home/go/src/github.com/go-delve/delve/service/rpccommon/server.go:112 +0xa8
github.com/go-delve/delve/cmd/dlv/cmds.execute(0x0, 0x40000745c0, 0x1, 0x1, 0x4000221f80, 0x0, 0x0, 0x1, 0x4000074550, 0x1, ...)
        /data/data/com.termux/files/home/go/src/github.com/go-delve/delve/cmd/dlv/cmds/commands.go:856 +0x620
github.com/go-delve/delve/cmd/dlv/cmds.debugCmd.func1(0x4000218fc0, 0x4000074550, 0x1, 0x1, 0x0)
        /data/data/com.termux/files/home/go/src/github.com/go-delve/delve/cmd/dlv/cmds/commands.go:473 +0x330
github.com/go-delve/delve/cmd/dlv/cmds.debugCmd(0x4000218fc0, 0x4000074550, 0x1, 0x1)
        /data/data/com.termux/files/home/go/src/github.com/go-delve/delve/cmd/dlv/cmds/commands.go:474 +0x38
github.com/go-delve/delve/vendor/github.com/spf13/cobra.(*Command).execute(0x4000218fc0, 0x4000074510, 0x1, 0x1, 0x4000218fc0, 0x4000074510)
        /data/data/com.termux/files/home/go/src/github.com/go-delve/delve/vendor/github.com/spf13/cobra/command.go:647 +0x17c
github.com/go-delve/delve/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x40002186c0, 0x40002186c0, 0x55a26dc582, 0x6)
        /data/data/com.termux/files/home/go/src/github.com/go-delve/delve/vendor/github.com/spf13/cobra/command.go:733 +0x1f8
github.com/go-delve/delve/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /data/data/com.termux/files/home/go/src/github.com/go-delve/delve/vendor/github.com/spf13/cobra/command.go:692
main.main()
        /data/data/com.termux/files/home/go/src/github.com/go-delve/delve/cmd/dlv/main.go:24 +0xb8
```

**Comment by derekparker** [comment]
IIUC Android just ends up running elf binaries anyways, this may be as simple as modifying verifyBinaryFormat to check for "android" in the switch checking `runtime.GOOS`.

**Comment by kcubeterm** [comment]
Adding "android" in switch fix error for now.
https://github.com/go-delve/delve/blob/master/service/debugger/debugger_unix.go

```go
switch runtime.GOOS {
        case "darwin":
                _, err = macho.NewFile(f)
        case "linux", "freebsd","android":
                _, err = elf.NewFile(f)
        default:
                panic("attempting to open file Delve cannot parse")
        }
        if err != nil {
                return api.ErrNotExecutable
        }
        return nil
```

**Comment by kcubeterm** [comment]
@derekparker Why delve have no support for android platform officially. Android is quite similar to linux and it requires few more lines of code to work on android.

**Comment by aarzilli** [comment]
> Why delve have no support for android platform officially. Android is quite similar to linux and it requires few more lines of code to work on android.

Nobody wrote those, and also CI availability.

**Comment by derekparker** [comment]
@kcubeterm feel free to submit a PR with Delve working on Android. Due to the lack of CI for it, it will mostly always be "best effort" to support it.

**Comment by kcubeterm** [comment]
I added Delve in termux [repo](https://github.com/termux/termux-packages/commit/8faf258b3f646c128f47dd7b0a2061b741973181)   and it works as expected. Didn't checked all features and subcommand yet. Leaving it on user. If user reports error. will try to fix it and submit PRs for sure if possible.

**Comment by Umsemana** [comment]
Oi

**Comment by fuwei199006** [comment]
Why is it not supported now?

**Comment by 61803** [comment]
> I added Delve in termux [repo](https://github.com/termux/termux-packages/commit/8faf258b3f646c128f47dd7b0a2061b741973181) and it works as expected. Didn't checked all features and subcommand yet. Leaving it on user. If user reports error. will try to fix it and submit PRs for sure if possible.

I got "Failed to launch: To debug executables using DWARFv5 or later Delve must be built with Go version 1.25.0 or later" error
