### ISSUE TITLE
Debugger crashes bininfo.go:1924

### ISSUE THREAD

**Issue by rspruyt-google** [go-delve/delve#2474]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?

Delve Debugger
Version: 1.6.0
Build: $Id: 8cc9751909843dd55a46e8ea2a561544f70db34d $

2. What version of Go are you using? (`go version`)?

go version go1.16.3 linux/amd64

3. What operating system and processor architecture are you using?

linux/x64

4. What did you do?

Ran a unit test for a project. Project runs, breakpoint has no effect (IntelliJ).

5. What did you expect to see?

stops at breakpoint

6. What did you see instead?

a go routine crash. 

panic: runtime error: index out of range [-1]

goroutine 6 [running]:
github.com/go-delve/delve/pkg/proc.(*BinaryInfo).loadDebugInfoMapsInlinedCalls(0xc0002b43c0, 0xc000284120, 0xc0001c80e0, 0xc00b05ed00)
	<redacted>/go/pkg/mod/github.com/go-delve/delve@v1.6.0/pkg/proc/bininfo.go:1924 +0xaa5
github.com/go-delve/delve/pkg/proc.(*BinaryInfo).addConcreteSubprogram(0xc0002b43c0, 0xc00ce59aa0, 0xc000284120, 0xc0001c80e0, 0xc00b05ed00)
	<redacted>/go/pkg/mod/github.com/go-delve/delve@v1.6.0/pkg/proc/bininfo.go:1854 +0x1d4
github.com/go-delve/delve/pkg/proc.(*BinaryInfo).loadDebugInfoMapsCompileUnit(0xc0002b43c0, 0xc000284120, 0xc0001da000, 0xc0001c80e0, 0xc00b05ed00)
	<redacted>/go/pkg/mod/github.com/go-delve/delve@v1.6.0/pkg/proc/bininfo.go:1748 +0xe25
github.com/go-delve/delve/pkg/proc.(*BinaryInfo).loadDebugInfoMaps(0xc0002b43c0, 0xc0001da000, 0xc0036ce000, 0x17168de, 0x17168de, 0xc002aca000, 0x88891a, 0x88891a, 0xc000123030, 0x0)
	<redacted>/go/pkg/mod/github.com/go-delve/delve@v1.6.0/pkg/proc/bininfo.go:1628 +0x731
created by github.com/go-delve/delve/pkg/proc.loadBinaryInfoElf
	<redacted>/go/pkg/mod/github.com/go-delve/delve@v1.6.0/pkg/proc/bininfo.go:1178 +0x5d2

Kindly reach out to me internally at Google @rspruyt, I will provide a test case to demonstrating the issue. 
I am not sure if this is related, but I'm seeing unit test failures on cloudtop as well w/ 'make' for both 1.6.0 and current head.

**Comment by aarzilli** [comment]
I fixed a bunch of things in this direction since 1.6.0 was released. Can you replicate this by building delve at master?

> Kindly reach out to me internally at Google @rspruyt, I will provide a test case to demonstrating the issue.

This code is not maintained by anyone that works at Google.

**Comment by aarzilli** [comment]
Yes, `make install`, and it doesn't run unit tests, so I'm not sure what you are seeing.

**Comment by rspruyt-google** [comment]
Thanks, sorry should have been 'make' not 'make install'

Installed TIP:

Delve Debugger
Version: 1.6.0
Build: 8057f5c96b2ca6b550fbe0139298091e6c7e41bf

and the issue seems to have been resolved as suggested. Thank you.
Here is the output of 'make' re: the unit tests failing.

```
--- FAIL: TestDWZCompression (0.40s)
    proc_test.go:1169: proc_test.go:3927: EvalVariable("stdin"): could not find symbol value for stdin
```

Full output:

```
rspruyt@rspruyt:~/delve$ git fetch origin
rspruyt@rspruyt:~/delve$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
rspruyt@rspruyt:~/delve$ make
Testing default backend
ok  	github.com/go-delve/delve/cmd/dlv	32.259s
ok  	github.com/go-delve/delve/cmd/dlv/cmds	0.037s
?   	github.com/go-delve/delve/pkg/astutil	[no test files]
ok  	github.com/go-delve/delve/pkg/config	0.012s
?   	github.com/go-delve/delve/pkg/dwarf/dwarfbuilder	[no test files]
ok  	github.com/go-delve/delve/pkg/dwarf/frame	0.011s
ok  	github.com/go-delve/delve/pkg/dwarf/godwarf	0.011s
ok  	github.com/go-delve/delve/pkg/dwarf/line	1.241s
ok  	github.com/go-delve/delve/pkg/dwarf/loclist	0.011s
ok  	github.com/go-delve/delve/pkg/dwarf/op	0.011s
?   	github.com/go-delve/delve/pkg/dwarf/reader	[no test files]
?   	github.com/go-delve/delve/pkg/dwarf/regnum	[no test files]
ok  	github.com/go-delve/delve/pkg/dwarf/util	0.012s
?   	github.com/go-delve/delve/pkg/elfwriter	[no test files]
?   	github.com/go-delve/delve/pkg/gobuild	[no test files]
ok  	github.com/go-delve/delve/pkg/goversion	0.020s
ok  	github.com/go-delve/delve/pkg/locspec	0.017s
?   	github.com/go-delve/delve/pkg/logflags	[no test files]
Hello, World!
Hello, World!
past main
100000
200000
300000
400000
500000
600000
700000
800000
900000
1000000
1100000
1200000
1300000
1400000
1500000
1600000
1700000
1800000
1900000
2000000
2100000
2200000
2300000
2400000
2500000
2600000
2700000
2800000
2900000
3000000
3100000
3200000
3300000
3400000
3500000
3600000
3700000
3800000
3900000
4000000
4100000
4200000
4300000
4400000
4500000
4600000
4700000
4800000
4900000
5000000
5100000
5200000
5300000
5400000
5500000
5600000
5700000
5800000
5900000
6000000
6100000
6200000
6300000
6400000
6500000
6600000
6700000
6800000
6900000
7000000
7100000
7200000
7300000
7400000
7500000
7600000
7700000
7800000
7900000
8000000
8100000
8200000
8300000
8400000
8500000
8600000
8700000
8800000
8900000
9000000
9100000
9200000
9300000
9400000
9500000
9600000
9700000
9800000
9900000
10000000
10100000
10200000
10300000
10400000
10500000
10600000
10700000
10800000
10900000
11000000
11100000
11200000
11300000
11400000
11500000
11600000
11700000
11800000
11900000
12000000
12100000
12200000
12300000
12400000
12500000
12600000
12700000
12800000
12900000
13000000
13100000
13200000
13300000
13400000
13500000
13600000
13700000
13800000
13900000
14000000
14100000
14200000
14300000
14400000
14500000
14600000
14700000
14800000
14900000
15000000
15100000
15200000
15300000
15400000
15500000
15600000
15700000
15800000
15900000
16000000
16100000
16200000
16300000
16400000
16500000
16600000
16700000
16800000
16900000
17000000
17100000
17200000
17300000
17400000
17500000
17600000
17700000
17800000
17900000
18000000
18100000
18200000
18300000
18400000
18500000
18600000
18700000
18800000
18900000
19000000
19100000
19200000
19300000
19400000
19500000
19600000
19700000
19800000
19900000
20000000
20100000
20200000
20300000
20400000
20500000
20600000
20700000
20800000
20900000
21000000
21100000
21200000
21300000
21400000
21500000
21600000
21700000
21800000
21900000
22000000
22100000
22200000
22300000
22400000
22500000
22600000
22700000
22800000
22900000
23000000
23100000
23200000
23300000
23400000
23500000
23600000
23700000
23800000
23900000
24000000
24100000
24200000
24300000
24400000
24500000
24600000
24700000
24800000
24900000
25000000
25100000
25200000
25300000
25400000
25500000
25600000
25700000
25800000
25900000
26000000
26100000
26200000
26300000
26400000
26500000
26600000
26700000
26800000
26900000
27000000
27100000
27200000
27300000
27400000
27500000
27600000
27700000
27800000
27900000
28000000
28100000
28200000
28300000
28400000
28500000
28600000
28700000
28800000
28900000
29000000
29100000
29200000
29300000
29400000
29500000
29600000
29700000
29800000
29900000
30000000
30100000
30200000
30300000
30400000
30500000
30600000
30700000
30800000
30900000
31000000
31100000
31200000
31300000
31400000
31500000
31600000
31700000
31800000
31900000
32000000
32100000
32200000
32300000
32400000
32500000
32600000
32700000
32800000
32900000
33000000
33100000
33200000
33300000
33400000
33500000
33600000
33700000
33800000
33900000
34000000
34100000
34200000
34300000
34400000
34500000
34600000
34700000
34800000
34900000
35000000
35100000
35200000
35300000
35400000
35500000
35600000
35700000
35800000
35900000
36000000
36100000
36200000
36300000
36400000
36500000
36600000
36700000
36800000
36900000
37000000
37100000
37200000
37300000
37400000
37500000
37600000
37700000
37800000
37900000
38000000
38100000
38200000
38300000
38400000
38500000
38600000
38700000
38800000
38900000
39000000
39100000
39200000
39300000
39400000
39500000
39600000
39700000
39800000
39900000
40000000
40100000
40200000
40300000
40400000
40500000
40600000
40700000
40800000
foo
hi 9
hi 3
hi 7
hi 9
hi 7
hi 0
hi 9
hi 9
hi 0
foo
Hello, World!
bye
hi
hi
hi
Tue 11 May 2021 05:45:59 PM UTC
id: 1 step: 0 sleeping 2
id: 2 step: 0 sleeping 8
id: 1 step: 1 sleeping 8
id: 2 step: 1 sleeping 10
id: 1 step: 2 sleeping 2
id: 1 step: 3 sleeping 9
id: 2 step: 2 sleeping 6
id: 1 step: 4 sleeping 1
id: 2 step: 3 sleeping 7
id: 1 step: 5 sleeping 1
id: 1 step: 6 sleeping 5
id: 2 step: 4 sleeping 2
id: 1 step: 7 sleeping 3
id: 2 step: 5 sleeping 10
id: 1 step: 8 sleeping 9
id: 2 step: 6 sleeping 5
id: 1 step: 9 sleeping 2
id: 1 step: 10 sleeping 6
id: 2 step: 7 sleeping 8
id: 1 step: 11 sleeping 7
id: 2 step: 8 sleeping 6
id: 1 step: 12 sleeping 7
id: 2 step: 9 sleeping 9
id: 1 step: 13 sleeping 9
id: 2 step: 10 sleeping 8
id: 1 step: 14 sleeping 8
id: 2 step: 11 sleeping 8
id: 1 step: 15 sleeping 9
id: 2 step: 12 sleeping 1
id: 2 step: 13 sleeping 6
id: 1 step: 16 sleeping 2
id: 2 step: 14 sleeping 9
id: 1 step: 17 sleeping 8
id: 2 step: 15 sleeping 2
id: 1 step: 18 sleeping 10
id: 2 step: 16 sleeping 7
id: 2 step: 17 sleeping 8
id: 1 step: 19 sleeping 2
id: 1 step: 20 sleeping 6
id: 2 step: 18 sleeping 7
id: 1 step: 21 sleeping 4
id: 2 step: 19 sleeping 1
id: 1 step: 22 sleeping 5
id: 2 step: 20 sleeping 4
id: 1 step: 23 sleeping 4
id: 2 step: 21 sleeping 8
id: 1 step: 24 sleeping 9
id: 2 step: 22 sleeping 5
id: 1 step: 25 sleeping 10
id: 2 step: 23 sleeping 4
id: 2 step: 24 sleeping 8
id: 1 step: 26 sleeping 2
id: 2 step: 25 sleeping 10
id: 1 step: 27 sleeping 10
id: 1 step: 28 sleeping 1
id: 2 step: 26 sleeping 6
id: 1 step: 29 sleeping 9
id: 2 step: 27 sleeping 9
id: 1 step: 30 sleeping 4
id: 1 step: 31 sleeping 6
id: 2 step: 28 sleeping 2
id: 2 step: 29 sleeping 1
id: 2 step: 30 sleeping 6
id: 1 step: 32 sleeping 7
id: 2 step: 31 sleeping 7
id: 1 step: 33 sleeping 9
id: 2 step: 32 sleeping 2
id: 2 step: 33 sleeping 3
id: 1 step: 34 sleeping 4
id: 2 step: 34 sleeping 7
id: 1 step: 35 sleeping 4
id: 2 step: 35 sleeping 7
id: 1 step: 36 sleeping 3
id: 1 step: 37 sleeping 9
id: 2 step: 36 sleeping 8
id: 1 step: 38 sleeping 5
id: 2 step: 37 sleeping 8
id: 1 step: 39 sleeping 4
id: 2 step: 38 sleeping 7
id: 1 step: 40 sleeping 1
id: 1 step: 41 sleeping 4
id: 1 step: 42 sleeping 4
id: 2 step: 39 sleeping 8
id: 1 step: 43 sleeping 4
id: 2 step: 40 sleeping 2
id: 1 step: 44 sleeping 10
id: 2 step: 41 sleeping 4
id: 2 step: 42 sleeping 4
id: 1 step: 45 sleeping 2
id: 2 step: 43 sleeping 3
id: 1 step: 46 sleeping 9
id: 2 step: 44 sleeping 7
id: 1 step: 47 sleeping 7
id: 2 step: 45 sleeping 8
id: 1 step: 48 sleeping 1
id: 2 step: 46 sleeping 4
id: 1 step: 49 sleeping 3
id: 2 step: 47 sleeping 4
id: 1 step: 50 sleeping 6
id: 2 step: 48 sleeping 9
id: 1 step: 51 sleeping 6
id: 1 step: 52 sleeping 2
id: 2 step: 49 sleeping 6
id: 1 step: 53 sleeping 8
id: 2 step: 50 sleeping 8
id: 1 step: 54 sleeping 1
id: 1 step: 55 sleeping 1
id: 1 step: 56 sleeping 6
id: 2 step: 51 sleeping 1
id: 2 step: 52 sleeping 3
id: 1 step: 57 sleeping 9
id: 2 step: 53 sleeping 4
id: 2 step: 54 sleeping 2
id: 2 step: 55 sleeping 3
id: 1 step: 58 sleeping 5
id: 2 step: 56 sleeping 8
id: 1 step: 59 sleeping 8
id: 2 step: 57 sleeping 8
id: 1 step: 60 sleeping 2
id: 1 step: 61 sleeping 5
id: 2 step: 58 sleeping 7
id: 1 step: 62 sleeping 3
id: 2 step: 59 sleeping 2
id: 1 step: 63 sleeping 10
id: 2 step: 60 sleeping 7
id: 1 step: 64 sleeping 1
id: 2 step: 61 sleeping 4
id: 1 step: 65 sleeping 7
id: 2 step: 62 sleeping 10
id: 1 step: 66 sleeping 2
id: 1 step: 67 sleeping 3
id: 2 step: 63 sleeping 6
id: 1 step: 68 sleeping 6
id: 1 step: 69 sleeping 1
id: 2 step: 64 sleeping 8
id: 1 step: 70 sleeping 10
id: 2 step: 65 sleeping 9
id: 1 step: 71 sleeping 9
id: 2 step: 66 sleeping 5
id: 1 step: 72 sleeping 4
id: 2 step: 67 sleeping 5
id: 1 step: 73 sleeping 8
id: 2 step: 68 sleeping 3
id: 2 step: 69 sleeping 3
id: 1 step: 74 sleeping 7
id: 2 step: 70 sleeping 10
id: 1 step: 75 sleeping 1
id: 1 step: 76 sleeping 7
id: 2 step: 71 sleeping 2
id: 2 step: 72 sleeping 7
id: 1 step: 77 sleeping 1
id: 1 step: 78 sleeping 2
id: 2 step: 73 sleeping 5
id: 1 step: 79 sleeping 5
id: 1 step: 80 sleeping 6
id: 2 step: 74 sleeping 4
id: 2 step: 75 sleeping 2
id: 1 step: 81 sleeping 1
id: 2 step: 76 sleeping 3
id: 1 step: 82 sleeping 9
id: 2 step: 77 sleeping 8
id: 1 step: 83 sleeping 2
id: 2 step: 78 sleeping 9
id: 1 step: 84 sleeping 5
id: 1 step: 85 sleeping 3
id: 2 step: 79 sleeping 4
id: 1 step: 86 sleeping 3
id: 2 step: 80 sleeping 9
id: 1 step: 87 sleeping 4
id: 1 step: 88 sleeping 9
id: 2 step: 81 sleeping 7
id: 1 step: 89 sleeping 1
id: 1 step: 90 sleeping 6
id: 2 step: 82 sleeping 1
id: 2 step: 83 sleeping 5
id: 1 step: 91 sleeping 3
id: 2 step: 84 sleeping 8
id: 1 step: 92 sleeping 6
id: 1 step: 93 sleeping 2
id: 2 step: 85 sleeping 10
id: 1 step: 94 sleeping 1
id: 1 step: 95 sleeping 4
id: 1 step: 96 sleeping 1
id: 2 step: 86 sleeping 10
id: 1 step: 97 sleeping 1
id: 1 step: 98 sleeping 4
id: 1 step: 99 sleeping 1
id: 2 step: 87 sleeping 5
id: 2 step: 88 sleeping 8
id: 2 step: 89 sleeping 1
id: 2 step: 90 sleeping 6
id: 2 step: 91 sleeping 3
id: 2 step: 92 sleeping 10
id: 2 step: 93 sleeping 1
id: 2 step: 94 sleeping 9
id: 2 step: 95 sleeping 7
id: 2 step: 96 sleeping 6
id: 2 step: 97 sleeping 7
id: 2 step: 98 sleeping 1
id: 2 step: 99 sleeping 7
2
0
1
2
hi 0
hi 0
hi 4
hi 4
hi 3
hi 3
hi 6
hi 6
hi 9
hi 9
hi 9
hi 3
hi 3
[]
[Todd]
[]
[Todd]
[Todd]
--- FAIL: TestPackageVariables (0.52s)
    support.go:252: enabling recording for github.com/go-delve/delve/pkg/proc_test.TestPackageVariables
    proc_test.go:1842: Unreadable variable reflect.arenaChunkIface: interface type "reflect.arenaChunkHeader" not found for 0x54ca78: no type entry found, use 'types' for a list of valid types
    proc_test.go:1846: previous errors
received args []string{"/tmp/testargs.9d6efeb3", "test"}
received args []string{"/tmp/testargs.9d6efeb3", "-test"}
received args []string{"/tmp/testargs.9d6efeb3", "test", "pass flag"}
received args []string{"/tmp/testargs.9d6efeb3", "test pass", "flag"}
received args []string{"/tmp/testargs.9d6efeb3", "test", "pass", "flag"}
received args []string{"/tmp/testargs.9d6efeb3", "test pass flag"}
received args []string{"/tmp/testargs.9d6efeb3"}
received args []string{"/tmp/testargs.9d6efeb3", "invalid"}
received args []string{"/tmp/testargs.9d6efeb3", "test", "invalid"}
received args []string{"/tmp/testargs.9d6efeb3", "invalid", "pass flag"}
hi 6
hi 7
hi 6
hi 0
hi 7
hi 4
hi 4
hi 2
hi 5
hi 5
hi 8
hi 2
hi 8
hi 9
hi 9
hi 8
hi 3
hi 7
hi 6
hi 8
hi 3
hi 7
hi 6
hi 4
hi 9
hi 9
hi 4
foo
foo
Hello, World!
z=9900
bye
hi
4
--- FAIL: TestDWZCompression (0.40s)
    proc_test.go:1169: proc_test.go:3927: EvalVariable("stdin"): could not find symbol value for stdin
i: 0 -> equalsTwo: false 
i: 1 -> equalsTwo: false 
0
fatal error: all goroutines are asleep - deadlock!
foo
Hello, World!
z=9900
fatal error: unexpected signal during runtime execution
1
fatal error: unexpected signal during runtime execution
0 1
2 1
2 4
5 4
id: 2 step: 0 sleeping 2
id: 1 step: 0 sleeping 8
id: 2 step: 1 sleeping 8
id: 1 step: 1 sleeping 10
id: 2 step: 2 sleeping 2
id: 2 step: 3 sleeping 9
id: 1 step: 2 sleeping 6
id: 2 step: 4 sleeping 1
id: 2 step: 5 sleeping 7
id: 1 step: 3 sleeping 1
id: 1 step: 4 sleeping 5
id: 2 step: 6 sleeping 2
id: 1 step: 5 sleeping 3
id: 2 step: 7 sleeping 10
id: 1 step: 6 sleeping 9
id: 2 step: 8 sleeping 5
id: 1 step: 7 sleeping 2
id: 2 step: 9 sleeping 6
id: 1 step: 8 sleeping 8
id: 2 step: 10 sleeping 7
id: 1 step: 9 sleeping 6
id: 2 step: 11 sleeping 7
id: 1 step: 10 sleeping 9
id: 2 step: 12 sleeping 9
id: 1 step: 11 sleeping 8
id: 2 step: 13 sleeping 8
id: 1 step: 12 sleeping 8
id: 2 step: 14 sleeping 9
id: 1 step: 13 sleeping 1
id: 1 step: 14 sleeping 6
id: 2 step: 15 sleeping 2
id: 1 step: 15 sleeping 9
id: 2 step: 16 sleeping 8
id: 1 step: 16 sleeping 2
id: 2 step: 17 sleeping 10
id: 1 step: 17 sleeping 7
id: 1 step: 18 sleeping 8
id: 2 step: 18 sleeping 2
id: 2 step: 19 sleeping 6
id: 1 step: 19 sleeping 7
id: 2 step: 20 sleeping 4
id: 2 step: 21 sleeping 1
id: 1 step: 20 sleeping 5
id: 2 step: 22 sleeping 4
id: 1 step: 21 sleeping 4
id: 2 step: 23 sleeping 8
id: 1 step: 22 sleeping 9
id: 2 step: 24 sleeping 5
id: 2 step: 25 sleeping 10
id: 1 step: 23 sleeping 4
id: 1 step: 24 sleeping 8
id: 2 step: 26 sleeping 2
id: 2 step: 27 sleeping 10
id: 1 step: 25 sleeping 10
id: 1 step: 26 sleeping 1
id: 2 step: 28 sleeping 6
id: 1 step: 27 sleeping 9
id: 2 step: 29 sleeping 9
id: 1 step: 28 sleeping 4
id: 1 step: 29 sleeping 6
id: 2 step: 30 sleeping 2
id: 2 step: 31 sleeping 1
id: 2 step: 32 sleeping 6
id: 1 step: 30 sleeping 7
id: 2 step: 33 sleeping 7
id: 1 step: 31 sleeping 9
id: 2 step: 34 sleeping 2
id: 2 step: 35 sleeping 3
id: 1 step: 32 sleeping 4
id: 2 step: 36 sleeping 7
id: 1 step: 33 sleeping 4
id: 1 step: 34 sleeping 7
id: 2 step: 37 sleeping 3
id: 2 step: 38 sleeping 9
id: 1 step: 35 sleeping 8
id: 2 step: 39 sleeping 5
id: 1 step: 36 sleeping 8
id: 2 step: 40 sleeping 4
id: 2 step: 41 sleeping 7
id: 1 step: 37 sleeping 1
id: 1 step: 38 sleeping 4
id: 1 step: 39 sleeping 4
id: 2 step: 42 sleeping 8
id: 1 step: 40 sleeping 4
id: 2 step: 43 sleeping 2
id: 1 step: 41 sleeping 10
id: 2 step: 44 sleeping 4
id: 2 step: 45 sleeping 4
id: 1 step: 42 sleeping 2
id: 1 step: 43 sleeping 3
id: 2 step: 46 sleeping 9
id: 1 step: 44 sleeping 7
id: 2 step: 47 sleeping 7
id: 1 step: 45 sleeping 8
id: 2 step: 48 sleeping 1
id: 2 step: 49 sleeping 4
id: 1 step: 46 sleeping 3
id: 2 step: 50 sleeping 4
id: 1 step: 47 sleeping 6
id: 2 step: 51 sleeping 9
id: 1 step: 48 sleeping 6
id: 1 step: 49 sleeping 2
id: 2 step: 52 sleeping 6
id: 1 step: 50 sleeping 8
id: 2 step: 53 sleeping 8
id: 1 step: 51 sleeping 1
id: 1 step: 52 sleeping 1
id: 1 step: 53 sleeping 6
id: 2 step: 54 sleeping 1
id: 2 step: 55 sleeping 3
id: 2 step: 56 sleeping 9
id: 1 step: 54 sleeping 4
id: 1 step: 55 sleeping 2
id: 1 step: 56 sleeping 3
id: 2 step: 57 sleeping 5
id: 1 step: 57 sleeping 8
id: 2 step: 58 sleeping 8
id: 1 step: 58 sleeping 8
id: 2 step: 59 sleeping 2
id: 2 step: 60 sleeping 5
id: 1 step: 59 sleeping 7
id: 2 step: 61 sleeping 3
id: 2 step: 62 sleeping 2
id: 1 step: 60 sleeping 10
id: 2 step: 63 sleeping 7
id: 2 step: 64 sleeping 1
id: 1 step: 61 sleeping 4
id: 2 step: 65 sleeping 7
id: 1 step: 62 sleeping 10
id: 2 step: 66 sleeping 2
id: 2 step: 67 sleeping 3
id: 1 step: 63 sleeping 6
id: 2 step: 68 sleeping 6
id: 1 step: 64 sleeping 1
id: 2 step: 69 sleeping 8
id: 1 step: 65 sleeping 10
id: 2 step: 70 sleeping 9
id: 1 step: 66 sleeping 9
id: 2 step: 71 sleeping 5
id: 1 step: 67 sleeping 4
id: 2 step: 72 sleeping 5
id: 1 step: 68 sleeping 8
id: 2 step: 73 sleeping 3
id: 2 step: 74 sleeping 3
id: 1 step: 69 sleeping 7
id: 2 step: 75 sleeping 10
id: 1 step: 70 sleeping 1
id: 1 step: 71 sleeping 7
id: 2 step: 76 sleeping 2
id: 2 step: 77 sleeping 7
id: 1 step: 72 sleeping 1
id: 1 step: 73 sleeping 2
id: 1 step: 74 sleeping 5
id: 2 step: 78 sleeping 5
id: 1 step: 75 sleeping 6
id: 2 step: 79 sleeping 4
id: 1 step: 76 sleeping 2
id: 2 step: 80 sleeping 1
id: 2 step: 81 sleeping 3
id: 1 step: 77 sleeping 9
id: 2 step: 82 sleeping 8
id: 1 step: 78 sleeping 2
id: 2 step: 83 sleeping 9
id: 1 step: 79 sleeping 5
id: 1 step: 80 sleeping 3
id: 2 step: 84 sleeping 4
id: 1 step: 81 sleeping 3
id: 1 step: 82 sleeping 9
id: 2 step: 85 sleeping 4
id: 2 step: 86 sleeping 9
id: 1 step: 83 sleeping 7
id: 2 step: 87 sleeping 1
id: 1 step: 84 sleeping 6
id: 2 step: 88 sleeping 1
id: 2 step: 89 sleeping 5
id: 1 step: 85 sleeping 3
id: 2 step: 90 sleeping 8
id: 1 step: 86 sleeping 6
id: 2 step: 91 sleeping 2
id: 1 step: 87 sleeping 10
id: 2 step: 92 sleeping 1
id: 2 step: 93 sleeping 4
id: 2 step: 94 sleeping 1
id: 1 step: 88 sleeping 10
id: 2 step: 95 sleeping 1
id: 2 step: 96 sleeping 4
id: 2 step: 97 sleeping 1
id: 2 step: 98 sleeping 5
id: 1 step: 89 sleeping 8
id: 2 step: 99 sleeping 1
id: 1 step: 90 sleeping 6
id: 1 step: 91 sleeping 3
id: 1 step: 92 sleeping 10
id: 1 step: 93 sleeping 1
id: 1 step: 94 sleeping 9
id: 1 step: 95 sleeping 7
id: 1 step: 96 sleeping 6
id: 1 step: 97 sleeping 7
id: 1 step: 98 sleeping 1
id: 1 step: 99 sleeping 7
Start
Receive signal interrupt 
End
FAIL
FAIL	github.com/go-delve/delve/pkg/proc	89.660s
?   	github.com/go-delve/delve/pkg/proc/amd64util	[no test files]
ok  	github.com/go-delve/delve/pkg/proc/core	0.517s
?   	github.com/go-delve/delve/pkg/proc/core/minidump	[no test files]
?   	github.com/go-delve/delve/pkg/proc/fbsdutil	[no test files]
ok  	github.com/go-delve/delve/pkg/proc/gdbserial	0.812s
?   	github.com/go-delve/delve/pkg/proc/linutil	[no test files]
?   	github.com/go-delve/delve/pkg/proc/native	[no test files]
?   	github.com/go-delve/delve/pkg/proc/test	[no test files]
?   	github.com/go-delve/delve/pkg/proc/winutil	[no test files]
ok  	github.com/go-delve/delve/pkg/terminal	17.585s
?   	github.com/go-delve/delve/pkg/terminal/colorize	[no test files]
?   	github.com/go-delve/delve/pkg/terminal/starbind	[no test files]
?   	github.com/go-delve/delve/pkg/version	[no test files]
?   	github.com/go-delve/delve/service	[no test files]
ok  	github.com/go-delve/delve/service/api	0.013s
ok  	github.com/go-delve/delve/service/dap	21.680s
?   	github.com/go-delve/delve/service/dap/daptest	[no test files]
?   	github.com/go-delve/delve/service/dap/daptest/gen	[no test files]
ok  	github.com/go-delve/delve/service/debugger	1.165s
?   	github.com/go-delve/delve/service/rpc1	[no test files]
?   	github.com/go-delve/delve/service/rpc2	[no test files]
ok  	github.com/go-delve/delve/service/rpccommon	0.034s
ok  	github.com/go-delve/delve/service/test	75.451s
FAIL
exit status 1
make: *** [Makefile:16: test] Error 1
rspruyt@rspruyt:~/delve$ 
```

**Comment by aarzilli** [comment]
I wouldn't worry about either. What's the output of `dwz --version`? Also, is this a special google-only version of Go? What's this arenaChunkIface business?
