### ISSUE TITLE
panic in convertVariableToString

### ISSUE THREAD

**Issue by toy80** [go-delve/delve#2690]
1. What version of Delve are you using (`dlv version`)?

Delve Debugger
Version: 1.7.1
Build: $Id: 3bde2354aafb5a4043fd59838842c4cd4a8b6f0b $

2. What version of Go are you using? (`go version`)?

go version go1.17 windows/amd64

3. What operating system and processor architecture are you using?

Windows 10  64bits  Intel I7

4. What did you do?

expanding local variable "a" in vscode variables pane

```go 
package main
import (
	"fmt"
)
type Index uint8
func main() {
	a := []Index{1, 2, 3, 4}
	fmt.Println(a)
}
```

5. What did you expect to see?

no  Internal Error

6. What did you see instead?

a : []main.Index len: 4, cap: 4, [1,2,3,4]
 [2] Internal Error: runtime error: invalid memory address or nil pointer dereference

```
DAP server listening at: 127.0.0.1:57120
2021-09-06T15:35:54+08:00 error layer=dap recovered panic: runtime error: invalid memory address or nil pointer dereference
goroutine 18 [running]:
runtime/debug.Stack()
	C:/a/go/src/runtime/debug/stack.go:24 +0x65
github.com/go-delve/delve/service/dap.(*Server).recoverPanic(0xc00025a000, {0x12863e0, 0xc0000d75c0})
	C:/a/gopath/pkg/mod/github.com/go-delve/delve@v1.7.2-0.20210901173137-5d158820f694/service/dap/server.go:379 +0x66
panic({0x1137900, 0x15d5390})
	C:/a/go/src/runtime/panic.go:1038 +0x215
github.com/go-delve/delve/service/api.ConvertVar(0x0)
	C:/a/gopath/pkg/mod/github.com/go-delve/delve@v1.7.2-0.20210901173137-5d158820f694/service/api/conversions.go:170 +0x47
github.com/go-delve/delve/service/dap.(*Server).convertVariableWithOpts(0xc00025a000, 0x0, {0x0, 0x200}, 0x1)
	C:/a/gopath/pkg/mod/github.com/go-delve/delve@v1.7.2-0.20210901173137-5d158820f694/service/dap/server.go:2077 +0x5e
github.com/go-delve/delve/service/dap.(*Server).convertVariableToString(...)
	C:/a/gopath/pkg/mod/github.com/go-delve/delve@v1.7.2-0.20210901173137-5d158820f694/service/dap/server.go:2045
github.com/go-delve/delve/service/dap.(*Server).metadataToDAPVariables(0xc00025a000, 0xc0002c3680)
	C:/a/gopath/pkg/mod/github.com/go-delve/delve@v1.7.2-0.20210901173137-5d158820f694/service/dap/server.go:2002 +0x4dd
github.com/go-delve/delve/service/dap.(*Server).onVariablesRequest(0xc00025a000, 0xc0000d75c0)
	C:/a/gopath/pkg/mod/github.com/go-delve/delve@v1.7.2-0.20210901173137-5d158820f694/service/dap/server.go:1777 +0x1d5
github.com/go-delve/delve/service/dap.(*Server).handleRequest(0xc00025a000, {0x12863e0, 0xc0000d75c0})
	C:/a/gopath/pkg/mod/github.com/go-delve/delve@v1.7.2-0.20210901173137-5d158820f694/service/dap/server.go:592 +0x1d5a
github.com/go-delve/delve/service/dap.(*Server).serveDAPCodec(0xc00025a000)
	C:/a/gopath/pkg/mod/github.com/go-delve/delve@v1.7.2-0.20210901173137-5d158820f694/service/dap/server.go:370 +0x1c7
github.com/go-delve/delve/service/dap.(*Server).Run.func1()
	C:/a/gopath/pkg/mod/github.com/go-delve/delve@v1.7.2-0.20210901173137-5d158820f694/service/dap/server.go:335 +0x11e
created by github.com/go-delve/delve/service/dap.(*Server).Run
	C:/a/gopath/pkg/mod/github.com/go-delve/delve@v1.7.2-0.20210901173137-5d158820f694/service/dap/server.go:314 +0x5b

```

**Comment by aarzilli** [comment]
cc @polinasok

**Comment by polinasok** [comment]
Thank you for the issue report. Fix is pending for us to gracefully handle the case when we cannot convert the byte array due to the type being user-defined. @aarzilli Is this working is intended in the backend?
```
> main.main() ./foo.go:13 (PC: 0x10abb85)
     8:
     9: func main() {
    10:         a := []Index{1, 2, 3, 4}
    11:         b := []uint8{1, 2, 3, 4}
    12:         fmt.Println(a)
=>  13:         fmt.Println(b)
    14: }
    15:
(dlv) p a
[]main.Index len: 4, cap: 4, [1,2,3,4]
(dlv) p b
[]uint8 len: 4, cap: 4, [1,2,3,4]
(dlv) p string(a)
Command failed: can not convert "a" to string
(dlv) p string(b)
"\x01\x02\x03\x04"
```
