### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by huahuayu** [go-delve/delve#2722]
## env

```bash
$ dlv version
Delve Debugger
Version: 1.7.2
Build: $Id: 5b6f24e7fbcad3fe3bc574d3763b2f20afa1d6a1 $
$ go version
go version go1.17.1 darwin/amd64
```

macos version 11.5.2 (20G95), intel

## problem

I upgraded `go-dlv` about two days, I debugged a program in goland ide, and get the below error, I think it's not related to my program, but I also have no idea what the root cause is, please take a look

```text
panic: runtime error: index out of range [7] with length 0

goroutine 112 [running]:
encoding/binary.littleEndian.Uint64(...)
        /opt/buildAgent/temp/buildTmp/go/src/encoding/binary/binary.go:77
github.com/go-delve/delve/pkg/proc/gdbserial.(*gdbRegisters).SP(0xc000353ef8, 0xc0006bfc10)
        /opt/buildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/gdbserial/gdbserver.go:1810 +0x85
github.com/go-delve/delve/pkg/proc.funcCallStep(0xc0025941e0, 0xc0006bfc10, 0x17255d8, 0xc000353ee0, 0xc, 0xc00244aac8, 0x13, 0x0)
        /opt/buildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/fncall.go:834 +0x74c
github.com/go-delve/delve/pkg/proc.evalFunctionCall(0xc0025941e0, 0xc0007bd140, 0xc000065cf0, 0x109cb76, 0x171e560)
        /opt/buildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/fncall.go:358 +0xa65
github.com/go-delve/delve/pkg/proc.(*EvalScope).evalAST(0xc0025941e0, 0x171d990, 0xc0007bd140, 0x1, 0x1, 0x64)
        /opt/buildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/eval.go:708 +0x312
github.com/go-delve/delve/pkg/proc.(*EvalScope).EvalExpression(0xc0025941e0, 0xc002b69740, 0x12, 0x1, 0x1, 0x64, 0x64, 0xffffffffffffffff, 0x0, 0x0, ...)
        /opt/buildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/eval.go:181 +0x69e
created by github.com/go-delve/delve/pkg/proc.EvalExpressionWithCalls
        /opt/buildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/fncall.go:197 +0x356

Debugger finished with the exit code 2
```

**Comment by aarzilli** [comment]
Can I see the log with `--log-output=rpc,gdbwire,fncall` passed to delve?

**Comment by huahuayu** [comment]
> Can I see the log with `--log-output=rpc,gdbwire,fncall` passed to delve?

how can I do this?

I tried
```
dlv --log-output=rpc,gdbwire,fncall
```

but seems not the case.

**Comment by aarzilli** [comment]
`dlv --log --log-output=rcp,gdbwire,fncall ...` I think this will only happen if you go through goland.

**Comment by huahuayu** [comment]
I think it's not related to goland, it occurs quit often(every times I set an break point), no matter v1.7.2 or 1.7.1
```
dlv --listen=127.0.0.1:56215 --headless=true --api-version=2 --check-go-version=false --only-same-user=false exec app -- --env=dev
API server listening at: 127.0.0.1:56215
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1205.0.28
 for x86_64.
Got a connection, launched process 
panic: runtime error: index out of range [7] with length 0

goroutine 50 [running]:
encoding/binary.littleEndian.Uint64(...)
        /usr/local/go/src/encoding/binary/binary.go:77
github.com/go-delve/delve/pkg/proc/gdbserial.(*gdbRegisters).SP(0xc003858428, 0xc0001e1c10)
        /Users/shiming/go/pkg/mod/github.com/go-delve/delve@v1.7.2/pkg/proc/gdbserial/gdbserver.go:1823 +0x85
github.com/go-delve/delve/pkg/proc.funcCallStep(0xc0009ae2d0, 0xc0001e1c10, 0x175c118, 0xc003858410, 0x0, 0xc001453b48, 0x13, 0x0)
        /Users/shiming/go/pkg/mod/github.com/go-delve/delve@v1.7.2/pkg/proc/fncall.go:834 +0x74c
github.com/go-delve/delve/pkg/proc.evalFunctionCall(0xc0009ae2d0, 0xc00145df40, 0xc000064cf0, 0x109c9f6, 0x1754f40)
        /Users/shiming/go/pkg/mod/github.com/go-delve/delve@v1.7.2/pkg/proc/fncall.go:358 +0xa65
github.com/go-delve/delve/pkg/proc.(*EvalScope).evalAST(0xc0009ae2d0, 0x1754340, 0xc00145df40, 0x1, 0x1, 0x64)
        /Users/shiming/go/pkg/mod/github.com/go-delve/delve@v1.7.2/pkg/proc/eval.go:708 +0x312
github.com/go-delve/delve/pkg/proc.(*EvalScope).EvalExpression(0xc0009ae2d0, 0xc0016186f0, 0x12, 0x1, 0x1, 0x64, 0x64, 0xffffffffffffffff, 0x0, 0x0, ...)
        /Users/shiming/go/pkg/mod/github.com/go-delve/delve@v1.7.2/pkg/proc/eval.go:181 +0x69e
created by github.com/go-delve/delve/pkg/proc.EvalExpressionWithCalls
        /Users/shiming/go/pkg/mod/github.com/go-delve/delve@v1.7.2/pkg/proc/fncall.go:197 +0x356
```

**Comment by aarzilli** [comment]
That's clearly a stacktrace for a function call, not for a breakpoint hit. But it doesn't matter, unless you post the logs or have a simple reproducer.

**Comment by aarzilli** [comment]
Ping? It would be interesting to know what causes this.

**Comment by aarzilli** [comment]
Closing, no user feedback.

**Comment by rentiansheng** [comment]
I need help.  I want to gdbRegisters  help document, 
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/3955934/230020830-ad28c171-4a79-4f0e-a1eb-c89d743f7933.png">
is not a necessary issue。 



info :
dlv:  git commit 4c40e8141d36bbd27a6b21ac850df9b3c6e3c805
golang: 1.20.3
macos: 13.0.1 (22A400)
cpu:  2.3 GHz 8-Core Intel Core i9
