### ISSUE TITLE
Delve panic when starting

### ISSUE THREAD

**Issue by vatzmehta** [go-delve/delve#2900]
1. What version of Delve are you using (`dlv version`)?
Version: 1.8.1
2. What version of Go are you using? (`go version`)?
go version go1.13.11 linux/amd64
3. What did you do?
Ran `dlv attach 3054 --listen=:8080 --headless --api-version=2 --accept-multiclient --check-go-version=false`
5. What did you expect to see?
Debugger to start
4. What did you see instead?
```API server listening at: [::]:3000
2022-02-08T17:13:36+05:30 warning layer=rpc Listening for remote connections (connections are not authenticated nor encrypted)
2022-02-08T17:13:36+05:30 error layer=debugger can't find build-id note on binary
2022-02-08T17:13:37+05:30 error layer=debugger can't find build-id note on binary
panic: runtime error: slice bounds out of range [:2] with length 0

goroutine 1 [running]:
github.com/go-delve/delve/pkg/proc.(*BinaryInfo).openSeparateDebugInfo(0xc0000c2c80, 0xc00518e000, 0xc005166d20, 0xc000162c80, 0x1, 0x1, 0x0, 0x203001, 0x8, 0x1007fe9897a4be0)
	/go/pkg/mod/github.com/go-delve/delve@v1.8.1/pkg/proc/bininfo.go:1213 +0xa5e
github.com/go-delve/delve/pkg/proc.loadBinaryInfoElf(0xc0000c2c80, 0xc00518e000, 0xc005d1f280, 0x18, 0x7fd7e7537000, 0xc005ca1290, 0x445b1e, 0xc00517eb20)
	/go/pkg/mod/github.com/go-delve/delve@v1.8.1/pkg/proc/bininfo.go:1297 +0x84a
github.com/go-delve/delve/pkg/proc.loadBinaryInfo(0xc0000c2c80, 0xc00518e000, 0xc005d1f280, 0x18, 0x7fd7e7537000, 0x0, 0x0)
	/go/pkg/mod/github.com/go-delve/delve@v1.8.1/pkg/proc/bininfo.go:671 +0x106
github.com/go-delve/delve/pkg/proc.(*BinaryInfo).AddImage(0xc0000c2c80, 0xc005d1f280, 0x18, 0x7fd7e7537000, 0x0, 0x0)
	/go/pkg/mod/github.com/go-delve/delve@v1.8.1/pkg/proc/bininfo.go:831 +0x2c4
github.com/go-delve/delve/pkg/proc/linutil.ElfUpdateSharedObjects(0xd9c040, 0xc000106510, 0xe, 0xc000162c80)
	/go/pkg/mod/github.com/go-delve/delve@v1.8.1/pkg/proc/linutil/dynamic.go:179 +0x1c9
github.com/go-delve/delve/pkg/proc/native.Attach(0xbee, 0xc000162c80, 0x1, 0x1, 0xc000199620, 0xc000199528, 0x40ba1b)
	/go/pkg/mod/github.com/go-delve/delve@v1.8.1/pkg/proc/native/proc_linux.go:165 +0x241
github.com/go-delve/delve/service/debugger.(*Debugger).Attach(0xc0000d4a50, 0xbee, 0x0, 0x0, 0xc0001995e0, 0x1, 0x1)
	/go/pkg/mod/github.com/go-delve/delve@v1.8.1/service/debugger/debugger.go:349 +0x137
github.com/go-delve/delve/service/debugger.New(0xc0001da000, 0xc00008af70, 0x0, 0x5, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/go-delve/delve@v1.8.1/service/debugger/debugger.go:160 +0x7f3
github.com/go-delve/delve/service/rpccommon.(*ServerImpl).Run(0xc00008b140, 0xc00008b140, 0xc000046420)
	/go/pkg/mod/github.com/go-delve/delve@v1.8.1/service/rpccommon/server.go:122 +0xcc
github.com/go-delve/delve/cmd/dlv/cmds.execute(0xbee, 0xc00008af70, 0x0, 0x5, 0xc0001705b0, 0x0, 0x0, 0x3, 0xc00008af60, 0x1, ...)
	/go/pkg/mod/github.com/go-delve/delve@v1.8.1/cmd/dlv/cmds/commands.go:971 +0x73f
github.com/go-delve/delve/cmd/dlv/cmds.attachCmd(0xc000188a00, 0xc00008af60, 0x1, 0x6)
	/go/pkg/mod/github.com/go-delve/delve@v1.8.1/cmd/dlv/cmds/commands.go:771 +0xfb
github.com/spf13/cobra.(*Command).execute(0xc000188a00, 0xc00008af00, 0x6, 0x6, 0xc000188a00, 0xc00008af00)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc000188780, 0xc000188780, 0xc6ba1f, 0x6)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
	/go/pkg/mod/github.com/go-delve/delve@v1.8.1/cmd/dlv/main.go:24 +0xc6```

**Comment by vatzmehta** [comment]
Thank you for the quick fix. dlv is starting when using the latest master :) 

Can we have 1.8.2 release for this since 
` go get github.com/go-delve/delve/cmd/dlv ` is still downloading older build

**Comment by aarzilli** [comment]
Go get is not the recommended way to install go applications anymore. You can either manually install the master version or change the configuration to not have a build-id directory in it.

Closing, because this was fixed by related PR.
