### ISSUE TITLE
dlv crashes in some cases on Windows

### ISSUE THREAD

**Issue by denisvmedia** [go-delve/delve#3010]
I'm experiencing problems with debugging with Delve on Windows 10 (I use Goland).

 `dlv version`:

```
Delve Debugger
Version: 1.8.3
Build: 10332d6700eba669d7dee8a560ca31acdf8fd6f5
```

`go version`:

```
go version go1.18.2 windows/amd64
```

I tried setting a breakpoint on a line in the code, but every time the execution reaches it, delve crashes with the following error stack trace:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0xe8 pc=0xdd4238]

goroutine 50 [running]:
github.com/go-delve/delve/pkg/proc.(*Variable).maybeDereference(0xc002d78120?)
	Z:/BuildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/variables.go:1187 +0x18
github.com/go-delve/delve/pkg/proc.convertToEface(0xc002d78120, 0xc002d78480)
	Z:/BuildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/variables.go:1370 +0x117
github.com/go-delve/delve/pkg/proc.(*EvalScope).setValue(0x690000?, 0xc002d78480, 0xc002d78120, {0xc002d70da0, 0x3})
	Z:/BuildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/eval.go:358 +0xf0
github.com/go-delve/delve/pkg/proc.funcCallCopyOneArg(0xc003c92ff0, 0xc0006091e8?, 0xc002d78120, 0xc003d4ed00?, 0xc002d721e0?)
	Z:/BuildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/fncall.go:630 +0x339
github.com/go-delve/delve/pkg/proc.funcCallEvalArgs(0xc003c92ff0, 0xc0006091e8, 0xc0001af030?)
	Z:/BuildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/fncall.go:595 +0x22a
github.com/go-delve/delve/pkg/proc.funcCallStep(0xc003c92ff0, 0xc0006091e8, {0x11c0700, 0xc0001af030}, 0xc, {0xc00002fd28, 0x13})
	Z:/BuildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/fncall.go:906 +0x829
github.com/go-delve/delve/pkg/proc.evalFunctionCall(0xc003c92ff0, 0xc003d4ea80)
	Z:/BuildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/fncall.go:399 +0x1030
github.com/go-delve/delve/pkg/proc.(*EvalScope).evalTypeCastOrFuncCall.func1()
	Z:/BuildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/eval.go:860 +0x151
github.com/go-delve/delve/pkg/proc.(*EvalScope).evalTypeCastOrFuncCall(0xc003c92ff0, 0xc003d4ea80)
	Z:/BuildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/eval.go:882 +0x2e2
github.com/go-delve/delve/pkg/proc.(*EvalScope).evalAST(0x10e2567?, {0x11bc840?, 0xc003d4ea80?})
	Z:/BuildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/eval.go:748 +0x15c
github.com/go-delve/delve/pkg/proc.(*EvalScope).evalStructSelector(0xc0013dbf60?, 0xc003c59098)
	Z:/BuildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/eval.go:1292 +0x2c
github.com/go-delve/delve/pkg/proc.(*EvalScope).evalAST(0xc003c92ff0, {0x11bcde0?, 0xc003c59098?})
	Z:/BuildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/eval.go:790 +0x6d5
github.com/go-delve/delve/pkg/proc.funcCallEvalFuncExpr(0xc003c8f680?, 0xc000609bd8, 0x1)
	Z:/BuildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/fncall.go:502 +0xed
github.com/go-delve/delve/pkg/proc.funcCallStep(0xc003c92ff0, 0xc000609bd8, {0x11c0700, 0xc0001af030}, 0xc, {0xc00002fd28, 0x13})
	Z:/BuildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/fncall.go:875 +0x5f4
github.com/go-delve/delve/pkg/proc.evalFunctionCall(0xc003c92ff0, 0xc003d4eac0)
	Z:/BuildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/fncall.go:399 +0x1030
github.com/go-delve/delve/pkg/proc.(*EvalScope).evalTypeCastOrFuncCall(0xc000609d08?, 0xb2be73?)
	Z:/BuildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/eval.go:851 +0x52
github.com/go-delve/delve/pkg/proc.(*EvalScope).evalAST(0xc003b2f4e0?, {0x11bc840?, 0xc003d4eac0?})
	Z:/BuildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/eval.go:748 +0x15c
github.com/go-delve/delve/pkg/proc.(*EvalScope).EvalExpression(0xc003c92ff0, {0xc003b2f4e0, 0x20}, {0x1, 0x1, 0x64, 0x64, 0xffffffffffffffff, 0x0})
	Z:/BuildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/eval.go:194 +0x49c
created by github.com/go-delve/delve/pkg/proc.EvalExpressionWithCalls
	Z:/BuildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/fncall.go:200 +0x3e5
```

**Comment by aarzilli** [comment]
This is caused by a function call injection, not by hitting a breakpoint. I imagine you have an expression that gets evaluated automatically at every stop that's causing this. I'd like to know what it is and also what the code where it happens looks like.
If you really don't have any expression that could cause this then I want to see the output of `--log --log-output=rpc`.

**Comment by denisvmedia** [comment]
I don't have an expression. It's just a plain BP. I will try to find out how to add arguments to dlv in Goland and get back with the log.

**Comment by aarzilli** [comment]
> Do you still need the logs?

Didn't see the edit. Yes, I'd still like to see the logs and if possible a way to reproduce it.
