### ISSUE TITLE
<nil> not an int

### ISSUE THREAD

**Issue by juancrescente** [go-delve/delve#3095]
I run into this panic whenever I try to debug my go apps.

```
2022-08-08T16:42:23-03:00 error layer=dap recovered panic: <nil> not an Int
goroutine 84 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x64
github.com/go-delve/delve/service/dap.(*Session).recoverPanic(0x140002be000, {0x102bd2918, 0x1400572c040})
	/Users/user/go/pkg/mod/github.com/go-delve/delve@v1.9.0/service/dap/server.go:559 +0x48
panic({0x102b0e1a0, 0x140009471c0})
	/usr/local/go/src/runtime/panic.go:884 +0x204
go/constant.Uint64Val({0x0?, 0x0?})
	/usr/local/go/src/go/constant/value.go:519 +0x13c
github.com/go-delve/delve/pkg/proc.(*Variable).parseG(0x102bdbaf8?)
	/Users/user/go/pkg/mod/github.com/go-delve/delve@v1.9.0/pkg/proc/variables.go:900 +0x96c
github.com/go-delve/delve/pkg/proc.GetG({0x102bdbaf8, 0x14003ec4460})
	/Users/user/go/pkg/mod/github.com/go-delve/delve@v1.9.0/pkg/proc/variables.go:259 +0xc8
github.com/go-delve/delve/service/api.ConvertThread({0x102bdbaf8, 0x14003ec4460}, 0x0)
	/Users/user/go/pkg/mod/github.com/go-delve/delve@v1.9.0/service/api/conversions.go:108 +0x118
github.com/go-delve/delve/service/debugger.(*Debugger).state(0x14000240210, 0x0)
	/Users/user/go/pkg/mod/github.com/go-delve/delve@v1.9.0/service/debugger/debugger.go:584 +0x400
github.com/go-delve/delve/service/debugger.(*Debugger).Command(0x14000240210, 0x1400336fa10, 0x14005034a80)
	/Users/user/go/pkg/mod/github.com/go-delve/delve@v1.9.0/service/debugger/debugger.go:1276 +0x1240
github.com/go-delve/delve/service/dap.(*Session).resumeOnce(0x140002be000, {0x1029df210, 0x4}, 0x14003e2a1e0)
	/Users/user/go/pkg/mod/github.com/go-delve/delve@v1.9.0/service/dap/server.go:3443 +0x1d4
github.com/go-delve/delve/service/dap.(*Session).resumeOnceAndCheckStop(0x140002be000, {0x1029df210, 0x4}, 0x1400336fae0?)
	/Users/user/go/pkg/mod/github.com/go-delve/delve@v1.9.0/service/dap/server.go:3585 +0x28
github.com/go-delve/delve/service/dap.glob..func1(0x0?, {0x1029df210?, 0x0?}, 0x0?)
	/Users/user/go/pkg/mod/github.com/go-delve/delve@v1.9.0/service/dap/server.go:3581 +0x20
github.com/go-delve/delve/service/dap.(*Session).runUntilStop(0x140002be000, {0x1029df210, 0x4}, 0x102887280?)
	/Users/user/go/pkg/mod/github.com/go-delve/delve@v1.9.0/service/dap/server.go:3573 +0xb4
github.com/go-delve/delve/service/dap.(*Session).runUntilStopAndNotify(0x140002be000, {0x1029df210, 0x4}, 0x1400020e0d8?)
	/Users/user/go/pkg/mod/github.com/go-delve/delve@v1.9.0/service/dap/server.go:3454 +0x30
github.com/go-delve/delve/service/dap.(*Session).stepUntilStopAndNotify(0x140002be000, {0x1029df210, 0x4}, 0x140031e4050?, {0x0, 0x0}, 0x14003e2a1e0)
	/Users/user/go/pkg/mod/github.com/go-delve/delve@v1.9.0/service/dap/server.go:1904 +0x3ac
github.com/go-delve/delve/service/dap.(*Session).onNextRequest(0x0?, 0x1400572c040, 0x0?)
	/Users/user/go/pkg/mod/github.com/go-delve/delve@v1.9.0/service/dap/server.go:1805 +0x138
github.com/go-delve/delve/service/dap.(*Session).handleRequest.func3()
	/Users/user/go/pkg/mod/github.com/go-delve/delve@v1.9.0/service/dap/server.go:698 +0x68
created by github.com/go-delve/delve/service/dap.(*Session).handleRequest
	/Users/user/go/pkg/mod/github.com/go-delve/delve@v1.9.0/service/dap/server.go:696 +0x12e8

```
go env
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/user/Library/Caches/go-build"
GOENV="/Users/user/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/user/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/user/Documents/code/rtb/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7m/mnymf5ss1mz39ygdshyl69n40000gp/T/go-build3807218627=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by aarzilli** [comment]
We don't see this problem on our builders, is there anything interesting with your setup or the program you are building? Do you have a small reproducer? Does it happen with every program or just a specific one?

**Comment by juancrescente** [comment]
Apparently it is on a specific app. What can I do to debug this?

**Comment by juancrescente** [comment]
oh nice, @aarzilli thanks! Do I need to compile delve or how can apply that change?

**Comment by aarzilli** [comment]
`git clone https://github.com/aarzilli/delve --branch fix3095` make sure that vscode uses the new version.

**Comment by juancrescente** [comment]
so far so good, I was able to install, and vscode started working. Then for goland I had to update the delve path as explained [here](https://youtrack.jetbrains.com/issue/GO-13489#focus=Comments-27-6381064.0-0). Thanks!


```
git clone https://github.com/aarzilli/delve --branch fix3095
make build
make install
```
