### ISSUE TITLE
Cannot debug in VSCode

### ISSUE THREAD

**Issue by blacktop** [go-delve/delve#3128]
It was working great yesterday and all I did was reboot my laptop *(which makes me think the problem is on my system, but I've NEVER seen this error before)*

1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.9.1
Build: $Id: d81b9fd12bfa603f3cf7a4bc842398bd61c42940 $
```
2. What version of Go are you using? (`go version`)?
`go version go1.19 darwin/arm64`
3. What operating system and processor architecture are you using?
`macOS13beta6 M1 Max`
4. What did you do?

Tried to debug in VSCode

6. What did you expect to see?

Normal debug session

8. What did you see instead?
```
Build Error: go build -o /Users/blacktop/Developer/Github/blacktop/ipsw/cmd/ipsw/__debug_bin -gcflags all=-N -l ./main.go
# command-line-arguments
panic: unexpected 32-bit segment

goroutine 1 [running]:
cmd/link/internal/ld.machoCombineDwarf(0x1007b9798?, 0x14000c04090?, 0x1400008e000, {0x14001d5c280?, 0x1?}, {0x14005652000, 0x52})

/opt/homebrew/Cellar/go/1.19/libexec/src/cmd/link/internal/ld/macho_combine_dwarf.go:218 +0xfb4
cmd/link/internal/ld.(*Link).hostlink(0x1400014a000)
	/opt/homebrew/Cellar/go/1.19/libexec/src/cmd/link/internal/ld/lib.go:1824 +0x44b0
cmd/link/internal/ld.Main(_, {0x10, 0x20, 0x1, 0x1f, 0x1e, 0x7c00000, {0x1006effb4, 0x14}, {0x1006f3939, ...}, ...})
	/opt/homebrew/Cellar/go/1.19/libexec/src/cmd/link/internal/ld/main.go:378 +0x1444
main.main()
	/opt/homebrew/Cellar/go/1.19/libexec/src/cmd/link/main.go:72 +0xd98 (exit status 2)
```

**Comment by blacktop** [comment]
another reboot fixed it??
