### ISSUE TITLE
print tab complete panics if there are no local variables

### ISSUE THREAD

**Issue by arussellk** [go-delve/delve#3217]
Delve panics if you use tab to try to list local variables with an empty query and there are no local variables (i.e., `(dlv) p <tab>`). The problem is in the trie code, and I have proposed fix (TODO: add link with proposed fix).

1. What version of Delve are you using (`dlv version`)?
```
dlv version
Delve Debugger
Version: 1.20.1
Build: $Id: 96e65b6c615845d42e0e31d903f6475b0e4ece6e $
```

2. What version of Go are you using? (`go version`)?
```
go version
go version go1.19.4 darwin/amd64
```

3. What operating system and processor architecture are you using?

macOS darwin/amd64

4. What did you do?

I made a small program in `main.go`:
```
package main

import "fmt"

func main() {
	someLocal := "value"
	fmt.Println(someLocal)
}
```

Then I ran dlv and pressed `<tab>` after `p `:
```
dlv debug main.go
Type 'help' for list of commands.
(dlv) break main.main
Breakpoint 1 set at 0x10b2b8a for main.main() ./main.go:5
(dlv) c
> main.main() ./main.go:5 (hits goroutine(1):1 total:1) (PC: 0x10b2b8a)
     1:	package main
     2:
     3:	import "fmt"
     4:
=>   5:	func main() {
     6:		someLocal := "value"
     7:		fmt.Println(someLocal)
     8:	}
(dlv) p panic: runtime error: makeslice: cap out of range

goroutine 1 [running]:
github.com/derekparker/trie.collect(0xc000b8dda0)
	/Users/russell/go/pkg/mod/github.com/derekparker/trie@v0.0.0-20200317170641-1fdf38b7b0e9/trie.go:249 +0x87
github.com/derekparker/trie.fuzzycollect(0xc00026e650?, {0xc00026e650?, 0x0?, 0x30?})
	/Users/russell/go/pkg/mod/github.com/derekparker/trie@v0.0.0-20200317170641-1fdf38b7b0e9/trie.go:273 +0x8d
github.com/derekparker/trie.Trie.FuzzySearch({{0x0, 0x0}, 0xc000b8dda0, 0x0}, {0xc0003a62e0?, 0x0?})
	/Users/russell/go/pkg/mod/github.com/derekparker/trie@v0.0.0-20200317170641-1fdf38b7b0e9/trie.go:135 +0x7b
github.com/go-delve/delve/pkg/terminal.(*Term).Run.func1({0xc0003a62e0, 0x2})
	/Users/russell/go/pkg/mod/github.com/go-delve/delve@v1.20.1/pkg/terminal/terminal.go:276 +0x871
github.com/go-delve/liner.(*State).SetCompleter.func1({0xc0003a62d9, 0x2}, 0x2)
	/Users/russell/go/pkg/mod/github.com/go-delve/liner@v1.2.3-0.20220127212407-d32d89dd2a5d/common.go:200 +0x94
github.com/go-delve/liner.(*State).tabComplete(0xc0006a6000, {0xc00026f1e0, 0x6, 0x20}, {0xc00026f160, 0x2, 0x20}, 0xc00026ef10?)
	/Users/russell/go/pkg/mod/github.com/go-delve/liner@v1.2.3-0.20220127212407-d32d89dd2a5d/line.go:369 +0xb3
github.com/go-delve/liner.(*State).PromptWithSuggestion(0xc0006a6000, {0x1671714, 0x6}, {0x0, 0x0}, 0x0)
	/Users/russell/go/pkg/mod/github.com/go-delve/liner@v1.2.3-0.20220127212407-d32d89dd2a5d/line.go:830 +0x2405
github.com/go-delve/liner.(*State).Prompt(...)
	/Users/russell/go/pkg/mod/github.com/go-delve/liner@v1.2.3-0.20220127212407-d32d89dd2a5d/line.go:596
github.com/go-delve/delve/pkg/terminal.(*Term).promptForInput(0xc0000cc420)
	/Users/russell/go/pkg/mod/github.com/go-delve/delve@v1.20.1/pkg/terminal/terminal.go:401 +0x38
github.com/go-delve/delve/pkg/terminal.(*Term).Run(0xc0000cc420)
	/Users/russell/go/pkg/mod/github.com/go-delve/delve@v1.20.1/pkg/terminal/terminal.go:319 +0x785
github.com/go-delve/delve/cmd/dlv/cmds.connect({0x16704eb?, 0xc000136400?}, {0x1760b88?, 0xc000142c00?}, 0x0?, 0x0?)
	/Users/russell/go/pkg/mod/github.com/go-delve/delve@v1.20.1/cmd/dlv/cmds/commands.go:873 +0x1ab
github.com/go-delve/delve/cmd/dlv/cmds.execute(0x0, {0xc000120e60, 0x1, 0x1}, 0xc00029a000, {0x0, 0x0}, 0x1, {0xc000120e30, 0x1, ...}, ...)
	/Users/russell/go/pkg/mod/github.com/go-delve/delve@v1.20.1/cmd/dlv/cmds/commands.go:1023 +0xf1c
github.com/go-delve/delve/cmd/dlv/cmds.debugCmd.func1(0xc00028fc40?, {0xc000120e30?, 0x0?, 0x0?})
	/Users/russell/go/pkg/mod/github.com/go-delve/delve@v1.20.1/cmd/dlv/cmds/commands.go:549 +0x237
github.com/go-delve/delve/cmd/dlv/cmds.debugCmd(0xc00014b900?, {0xc000120e30?, 0x1?, 0x1?})
	/Users/russell/go/pkg/mod/github.com/go-delve/delve@v1.20.1/cmd/dlv/cmds/commands.go:550 +0x1e
github.com/spf13/cobra.(*Command).execute(0xc00014b900, {0xc000120e00, 0x1, 0x1})
	/Users/russell/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xc00014af00)
	/Users/russell/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x39d
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/russell/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
	/Users/russell/go/pkg/mod/github.com/go-delve/delve@v1.20.1/cmd/dlv/main.go:24 +0x18a
```

5. What did you expect to see?

No completion.

6. What did you see instead?

Delve panics with `panic: runtime error: makeslice: cap out of range`.

**Comment by derekparker** [comment]
The PR against Trie has been merged. Would you like to send an update to Delve to bump the dep?

**Comment by arussellk** [comment]
Yes. I opened https://github.com/go-delve/delve/pull/3219.
