### ISSUE TITLE
dlv exception when debug windows_exporter

### ISSUE THREAD

**Issue by peekjef72** [go-delve/delve#3320]
1. What version of Delve are you using (`dlv version`)?
latest: 1.20.1
```sh
>dlv.exe version
Delve Debugger
Version: 1.20.1
Build: $Id: 96e65b6c615845d42e0e31d903f6475b0e4ece6e $
```

2. What version of Go are you using? (`go version`)?
```sh
>go version
go version go1.20.2 windows/amd64
```

3. What operating system and processor architecture are you using?
```sh
Windows 10 version 21H2 - 64 bits
Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz   3.50 GHz 
```

4. What did you do?
expect to debug/trace the behavior of windows_exporter v 0.22.0
https://github.com/prometheus-community/windows_exporter
so try to launch from VS code => exception
try mannually with direct dlv debug => exception too.

5. What did you expect to see?
to debug config file parsing method...

6. What did you see instead?

```bash
>dlv.exe debug
Type 'help' for list of commands.
(dlv) c
Exception 0xc0000008 0x0 0x0 0x7ffed5c10fca
PC=0x7ffed5c10fca

runtime.cgocall(0x7ca2e0, 0x17e0000)
        C:/Program Files/Go/src/runtime/cgocall.go:157 +0x4a fp=0xc000145510 sp=0xc0001454d8 pc=0x75544a
syscall.SyscallN(0x7ffed4ac6790, {0xc0001455b8?, 0x3, 0xc0000b2040?})
        C:/Program Files/Go/src/runtime/syscall_windows.go:557 +0x12e fp=0xc000145598 sp=0xc000145510 pc=0x7c532e
syscall.Syscall(0xc00010e390?, 0x1010000000000?, 0x18b509e0d28?, 0x18b2af20598?, 0x0?)
        C:/Program Files/Go/src/runtime/syscall_windows.go:495 +0x3b fp=0xc0001455e0 sp=0xc000145598 pc=0x7c4f1b
syscall.RegCloseKey(0x80000004)
        C:/Program Files/Go/src/syscall/zsyscall_windows.go:301 +0x65 fp=0xc000145670 sp=0xc0001455e0 pc=0x84b9c5
github.com/leoluk/perflib_exporter/perflib.queryRawData({0x12e2aa3, 0xb})
        C:/Users/jfpik/go/pkg/mod/github.com/leoluk/perflib_exporter@v0.2.0/perflib/perflib.go:240 +0x673 fp=0xc000145950 sp=0xc000145670 pc=0xe7cb93
github.com/leoluk/perflib_exporter/perflib.QueryNameTable({0x12e2aa3, 0xb})
        C:/Users/jfpik/go/pkg/mod/github.com/leoluk/perflib_exporter@v0.2.0/perflib/nametable.go:41 +0xb1 fp=0xc000145bc8 sp=0xc000145950 pc=0xe7bf11
github.com/leoluk/perflib_exporter/perflib.init.0()
        C:/Users/jfpik/go/pkg/mod/github.com/leoluk/perflib_exporter@v0.2.0/perflib/perflib.go:273 +0x29 fp=0xc000145bf0 sp=0xc000145bc8 pc=0xe7d1e9
runtime.doInit(0x1785ec0)
        C:/Program Files/Go/src/runtime/proc.go:6506 +0x132 fp=0xc000145d20 sp=0xc000145bf0 pc=0x7a2cf2
runtime.doInit(0x178f9e0)
        C:/Program Files/Go/src/runtime/proc.go:6483 +0x79 fp=0xc000145e50 sp=0xc000145d20 pc=0x7a2c39
runtime.doInit(0x1789160)
        C:/Program Files/Go/src/runtime/proc.go:6483 +0x79 fp=0xc000145f80 sp=0xc000145e50 pc=0x7a2c39
runtime.main()
        C:/Program Files/Go/src/runtime/proc.go:233 +0x17f fp=0xc000145fe0 sp=0xc000145f80 pc=0x7954bf
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000145fe8 sp=0xc000145fe0 pc=0x7c8921

goroutine 2 [force gc (idle)]:
runtime.gopark(0x134e010, 0x17de380, 0x11, 0x14, 0x1)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xfd fp=0xc000063f88 sp=0xc000063f58 pc=0x79597d
runtime.goparkunlock(0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:387 +0x2a fp=0xc000063fb8 sp=0xc000063f88 pc=0x795a0a
runtime.forcegchelper()
        C:/Program Files/Go/src/runtime/proc.go:305 +0xb0 fp=0xc000063fe0 sp=0xc000063fb8 pc=0x795750
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000063fe8 sp=0xc000063fe0 pc=0x7c8921
created by runtime.init.6
        C:/Program Files/Go/src/runtime/proc.go:293 +0x25

goroutine 18 [GC sweep wait]:
runtime.gopark(0x134e010, 0x17df0c0, 0xc, 0x14, 0x1)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xfd fp=0xc00008ff58 sp=0xc00008ff28 pc=0x79597d
runtime.goparkunlock(0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:387 +0x2a fp=0xc00008ff88 sp=0xc00008ff58 pc=0x795a0a
runtime.bgsweep(0x0?)
        C:/Program Files/Go/src/runtime/mgcsweep.go:278 +0x98 fp=0xc00008ffc8 sp=0xc00008ff88 pc=0x77ab78
runtime.gcenable.func1()
        C:/Program Files/Go/src/runtime/mgc.go:178 +0x26 fp=0xc00008ffe0 sp=0xc00008ffc8 pc=0x76ef86
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00008ffe8 sp=0xc00008ffe0 pc=0x7c8921
created by runtime.gcenable
        C:/Program Files/Go/src/runtime/mgc.go:178 +0x6b

goroutine 19 [GC scavenge wait]:
runtime.gopark(0x134e010, 0x17df6a0, 0xd, 0x14, 0x2)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xfd fp=0xc000091f48 sp=0xc000091f18 pc=0x79597d
runtime.goparkunlock(0x13bddf8?, 0x1?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:387 +0x2a fp=0xc000091f78 sp=0xc000091f48 pc=0x795a0a
runtime.(*scavengerState).park(0x17df6a0)
        C:/Program Files/Go/src/runtime/mgcscavenge.go:400 +0x4b fp=0xc000091fa0 sp=0xc000091f78 pc=0x77862b
runtime.bgscavenge(0x0?)
        C:/Program Files/Go/src/runtime/mgcscavenge.go:628 +0x45 fp=0xc000091fc8 sp=0xc000091fa0 pc=0x778c05
runtime.gcenable.func2()
        C:/Program Files/Go/src/runtime/mgc.go:179 +0x26 fp=0xc000091fe0 sp=0xc000091fc8 pc=0x76ef26
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000091fe8 sp=0xc000091fe0 pc=0x7c8921
created by runtime.gcenable
        C:/Program Files/Go/src/runtime/mgc.go:179 +0xaa

goroutine 34 [finalizer wait]:
runtime.gopark(0x134dcf8, 0x18358f0, 0x10, 0x14, 0x1)
        C:/Program Files/Go/src/runtime/proc.go:381 +0xfd fp=0xc000067e28 sp=0xc000067df8 pc=0x79597d
runtime.runfinq()
        C:/Program Files/Go/src/runtime/mfinal.go:193 +0x107 fp=0xc000067fe0 sp=0xc000067e28 pc=0x76dfe7
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000067fe8 sp=0xc000067fe0 pc=0x7c8921
created by runtime.createfing
        C:/Program Files/Go/src/runtime/mfinal.go:163 +0x50
rax     0x5
rbx     0x0
rcx     0x5
rdi     0x7d4f95b000
rsi     0xc000145550
rbp     0xc000145500
rsp     0x7d4fbffa20
r8      0x7d4fbffb50
r9      0x7d4fbffb50
r10     0x7d4fbffad8
r11     0x0
r12     0x0
r13     0x0
r14     0xc000060000
r15     0x2030
rip     0x7ffed5c10fca
rflags  0x200
cs      0x33
fs      0x53
gs      0x2b
Process 27116 has exited with status 2
(dlv)
```

I don't know what that means because program behaves correctly when starting from host:

```bash
>go build

>windows_exporter.exe --version
windows_exporter, version  (branch: , revision: 813208389255bc5e638b6ae23465467090162aef)
  build user:
  build date:
  go version:       go1.20.2
  platform:         windows/amd64
  tags:             unknown
```
Any help appreciated !
Thanks

**Comment by aarzilli** [comment]
0xc0000008 is the invalid handle exception. Windows does this funny thing where some syscalls behave differently when you are running under a debugger. I think this is one of those cases, the program is probably doing something wrong with the RegCloseKey call (I do not know what) and windows will let it slide unless it is running under a debugger.
