### ISSUE TITLE
Attach - <nil> not an Int

### ISSUE THREAD

**Issue by benbuzbee** [go-delve/delve#3330]
Delve Debugger
Version: 1.20.2
Build: $Id: e0c278ad8e0126a312b553b8e171e81bcbd37f60 $

$ sudo dlv attach 914724
```
panic: <nil> not an Int

goroutine 1 [running]:
go/constant.Int64Val(0x0, 0x0, 0xc, 0xc006b4a000)
        go/constant/value.go:468 +0x17f
github.com/go-delve/delve/pkg/proc.(*Variable).parseG.func1(0xb4ccaf, 0xc, 0x9)
        github.com/go-delve/delve/pkg/proc/variables.go:856 +0x6b
github.com/go-delve/delve/pkg/proc.(*Variable).parseG(0xc006b0e240, 0xc000300000, 0xc006b0e240, 0x0)
        github.com/go-delve/delve/pkg/proc/variables.go:885 +0x4cb
github.com/go-delve/delve/pkg/proc.GetG(0xc211e0, 0xc000300000, 0xc00019e800, 0x7f3f5954d648, 0xc00019e800)
        github.com/go-delve/delve/pkg/proc/variables.go:255 +0xd3
github.com/go-delve/delve/pkg/proc.NewTarget(0xc22b20, 0xc00019e800, 0xc211e0, 0xc000300000, 0xc000280030, 0x10, 0xc000186c60, 0x1, 0x1, 0x10200, ...)
        github.com/go-delve/delve/pkg/proc/target.go:173 +0x249
github.com/go-delve/delve/pkg/proc/native.(*nativeProcess).initialize(0xc00019e800, 0xc000280030, 0x10, 0xc000186c60, 0x1, 0x1, 0x10, 0xa8, 0xb1c820)
        github.com/go-delve/delve/pkg/proc/native/proc.go:306 +0x15a
github.com/go-delve/delve/pkg/proc/native.Attach(0xdf524, 0xc000186c60, 0x1, 0x1, 0xc0001e7738, 0xc0001e7640, 0x40ce05)
        github.com/go-delve/delve/pkg/proc/native/proc_linux.go:147 +0x1fd
github.com/go-delve/delve/service/debugger.(*Debugger).Attach(0xc00021a000, 0xdf524, 0x0, 0x0, 0xc0001e76f8, 0x1, 0x1)
        github.com/go-delve/delve/service/debugger/debugger.go:344 +0x225
github.com/go-delve/delve/service/debugger.New(0xc000218000, 0xc000186e00, 0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/go-delve/delve/service/debugger/debugger.go:158 +0x80c
github.com/go-delve/delve/service/rpccommon.(*ServerImpl).Run(0xc000180720, 0xc000180720, 0xc0001c65a0)
        github.com/go-delve/delve/service/rpccommon/server.go:115 +0xcc
github.com/go-delve/delve/cmd/dlv/cmds.execute(0xdf524, 0xc000186e00, 0x0, 0x0, 0xc0001a0d00, 0x0, 0x0, 0x3, 0xc000186e00, 0x1, ...)
        github.com/go-delve/delve/cmd/dlv/cmds/commands.go:864 +0x7e5
github.com/go-delve/delve/cmd/dlv/cmds.attachCmd(0xc0001c2f00, 0xc000186e00, 0x1, 0x1)
        github.com/go-delve/delve/cmd/dlv/cmds/commands.go:671 +0x105
github.com/spf13/cobra.(*Command).execute(0xc0001c2f00, 0xc000186dd0, 0x1, 0x1, 0xc0001c2f00, 0xc000186dd0)
        github.com/spf13/cobra/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001c2c80, 0xc0001c2c80, 0xb454f3, 0x6)
        github.com/spf13/cobra/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra/command.go:897
main.main()
        github.com/go-delve/delve/cmd/dlv/main.go:24 +0xc7
```

**Comment by aarzilli** [comment]
This is a bug that existed when using old versions of delve with go 1.20. You say you are using delve 1.20.2 but the line numbers in your stacktrace do not line up with 1.20.2.

**Comment by benbuzbee** [comment]
I see, my mistake, sorry for the noise. Different version for root than CWD

$ sudo dlv version
Delve Debugger
Version: 1.6.1
Build: $Id: 114218c22f3791287c4bc2f4ff35a846a1416ee9 $

$ dlv version
Delve Debugger
Version: 1.20.2
Build: $Id: e0c278ad8e0126a312b553b8e171e81bcbd37f60 $
vagrant@cloudchamber-devbox:~/cloudchamber-nomad-driver$
