### ISSUE TITLE
arm64 core can not print local variable and input parameters after nil pointer dereference

### ISSUE THREAD

**Issue by gnlsw** [go-delve/delve#3587]
1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.21.2
Build: $Id: 98f8ab2662d926245917ade2f2bb38277315c7fc $
```
2. What version of Go are you using? (`go version`)?
`go version go1.20.10 linux/arm64`

3. What operating system and processor architecture are you using?
```
cat /etc/redhat-release
CentOS Linux release 7.9.2009 (AltArch)
```
4. What did you do?

demo.go

```
package main

func main() {
	map_value := make(map[string]*int)

	var value_1 int = 1
	var value_2 int = 2
	map_value["a"] = &value_1
	map_value["b"] = &value_2

	mod_map(map_value)
}

func mod_map(map_value map[string]*int) {
	p_value := map_value["c"]
	*p_value = 3
}
```

> step 1: Compile the demo.go with debug information (go build -gcflags "-N -l" demo.go)
> step 2: Run the executable file and generate the coredump file.
> step 3: Dlv coredump file and print the local variable and input parameters.

6. What did you expect to see?
We expect can print the local variable and input parameters correctly.

7. What did you see instead?
When we print local variable and input parameter, we get the wrong information.

**Comment by gnlsw** [comment]
The following is the detail information。

**srource file: demo.go**
```
package main

func main() {
	map_value := make(map[string]*int)

	var value_1 int = 1
	var value_2 int = 2
	map_value["a"] = &value_1
	map_value["b"] = &value_2

	mod_map(map_value)
}

func mod_map(map_value map[string]*int) {
	p_value := map_value["c"]
	*p_value = 3
}
```

**go build -gcflags "-N -l" demo.go
./demo**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x660a0]

goroutine 1 [running]:
panic({0x75ec0, 0xe1300})
        /home/wsl/go/go1.20.10/src/runtime/panic.go:987 +0x3ac fp=0x400021ed50 sp=0x400021ec90 pc=0x3bc4c
runtime.panicmem()
        /home/wsl/go/go1.20.10/src/runtime/panic.go:260 +0x48 fp=0x400021ed70 sp=0x400021ed50 pc=0x3a718
runtime.sigpanic()
        /home/wsl/go/go1.20.10/src/runtime/signal_unix.go:841 +0x214 fp=0x400021edb0 sp=0x400021ed70 pc=0x50b44
main.mod_map(0x4000160668)
        /home/wsl/demo2/demo_2.go:16 +0x40 fp=0x400021ee00 sp=0x400021edc0 pc=0x660a0
main.main()
        /home/wsl/demo2/demo_2.go:11 +0x158 fp=0x400021ef70 sp=0x400021ee00 pc=0x66048
runtime.main()
        /home/wsl/go/go1.20.10/src/runtime/proc.go:250 +0x200 fp=0x400021efd0 sp=0x400021ef70 pc=0x3e640
runtime.goexit()
        /home/wsl/go/go1.20.10/src/runtime/asm_arm64.s:1172 +0x4 fp=0x400021efd0 sp=0x400021efd0 pc=0x63af4
```
**[root@localhost demo]# dlv core demo core_demo_94409**
```
Type 'help' for list of commands.
(dlv) bt
 0  0x0000000000064948 in runtime.raise
    at /home/wsl/go/go1.20.10/src/runtime/sys_linux_arm64.s:158
 1  0x0000000000050bc4 in runtime.dieFromSignal
    at /home/wsl/go/go1.20.10/src/runtime/signal_unix.go:883
 2  0x00000000000510c8 in runtime.sigfwdgo
    at /home/wsl/go/go1.20.10/src/runtime/signal_unix.go:1096
 3  0x000000000004fbcc in runtime.sigtrampgo
    at /home/wsl/go/go1.20.10/src/runtime/signal_unix.go:432
 4  0x0000000000064948 in runtime.raise
    at /home/wsl/go/go1.20.10/src/runtime/sys_linux_arm64.s:157
 5  0x0000000000050bc4 in runtime.dieFromSignal
    at /home/wsl/go/go1.20.10/src/runtime/signal_unix.go:883
 6  0x000000000003c388 in runtime.crash
    at /home/wsl/go/go1.20.10/src/runtime/signal_unix.go:975
 7  0x000000000003c388 in runtime.fatalpanic
    at /home/wsl/go/go1.20.10/src/runtime/panic.go:1172
 8  0x000000000003bc4c in runtime.gopanic
    at /home/wsl/go/go1.20.10/src/runtime/panic.go:987
 9  0x000000000003a718 in runtime.panicmem
    at /home/wsl/go/go1.20.10/src/runtime/panic.go:260
10  0x0000000000050b44 in runtime.sigpanic
    at /home/wsl/go/go1.20.10/src/runtime/signal_unix.go:841
11  0x00000000000660a0 in main.mod_map
    at ./demo_2.go:15
12  0x00000000000660a0 in main.mod_map
    at ./demo_2.go:15
13  0x0000000000066098 in main.mod_map
    at ./demo_2.go:15
14  0x0000000000000000 in ???
    at :0
    error: NULL address
(truncated)
(dlv) frame 11
> runtime.raise() /home/wsl/go/go1.20.10/src/runtime/sys_linux_arm64.s:158 (PC: 0x64948)
Warning: debugging optimized function
Frame 11: ./demo_2.go:15 (PC: 660a0)
    10:
    11:         mod_map(map_value)
    12: }
    13:
    14: func mod_map(map_value map[string]*int) {
=>  15:         p_value := map_value["c"]
    16:         *p_value = 3
    17: }
(dlv) p map_value
map[string]*int []
(dlv) p p_value
Command failed: could not find symbol value for p_value
(dlv) q
```

**Comment by aarzilli** [comment]
You are debugging optimized code, so the fact that some variable is optimized out and unreadable is to be expected. Yes, you say that you did compile with `-gcflags=-N -l` but, first of all it should be `-gcflags=all=-N -l` and secondly you probably didn't actually do it, since it does apply to the main module anyway and you can see delve complaining about it (`Warning: debugging optimized function`).
