### ISSUE TITLE
panic when delve process is stopped

### ISSUE THREAD

**Issue by bo-er** [go-delve/delve#3723]
1. What version of Delve are you using (`dlv version`)?
```
[root@62-62-udp-5 opt]# dlv version
Delve Debugger
Version: 1.20.1
Build: $Id: 96e65b6c615845d42e0e31d903f6475b0e4ece6e $
[root@62-62-udp-5 opt]#
```
2. What version of Go are you using? (`go version`)?
irrelevant since the program has been compiled and was downloaded from release page of delve.
4. What operating system and processor architecture are you using?
```
CentOS Linux release 7.2.1511 (Core)
Linux 62-62-udp-5 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
5. What did you do?
Stopping delve
7. What did you expect to see?
``` 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x7fdcb8]

goroutine 1 [running]:
github.com/go-delve/delve/service/debugger.(*Debugger).Command(0xc000146790, 0xc000277790, 0x0)
        /root/go/pkg/mod/github.com/go-delve/delve@v1.20.1/service/debugger/debugger.go:1301 +0x1718
github.com/go-delve/delve/service/rpccommon.(*ServerImpl).Stop(0xc000122d20)
        /root/go/pkg/mod/github.com/go-delve/delve@v1.20.1/service/rpccommon/server.go:101 +0xee
github.com/go-delve/delve/cmd/dlv/cmds.execute(0x376e, {0xc000122b50, 0x0, 0x5}, 0xc00011a0e0, {0x0, 0x0}, 0x3, {0xc000122b40, 0x1, ...}, ...)
        /root/go/pkg/mod/github.com/go-delve/delve@v1.20.1/cmd/dlv/cmds/commands.go:1015 +0xea9
github.com/go-delve/delve/cmd/dlv/cmds.attachCmd(0xc0001ecc80?, {0xc000122b40?, 0x1, 0x6})
        /root/go/pkg/mod/github.com/go-delve/delve@v1.20.1/cmd/dlv/cmds/commands.go:791 +0x145
github.com/spf13/cobra.(*Command).execute(0xc0001ecc80, {0xc000122ae0, 0x6, 0x6})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001eca00)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x39d
github.com/spf13/cobra.(*Command).Execute(0xaa7f00?)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897 +0x19
main.main()
        /root/go/pkg/mod/github.com/go-delve/delve@v1.20.1/cmd/dlv/main.go:24 +0x18a
```
Should not panic
9. What did you see instead?
delve panics

**Comment by aarzilli** [comment]
Do you have some steps to reproduce this? Does this reproduce with delve 1.22?

**Comment by aarzilli** [comment]
Closing, no feedback.
